#!/bin/bash

set -e

trap ctrl_c INT

function ctrl_c() {
        echo
	echo "Ctrl-C by user"
	kill -9 $pid
	exit
}

args=$@
tensorboard_exec="tensorboard --reload_interval 0"

while true
do
	eval "$tensorboard_exec $args &"
	pid=$!
	echo "tensorboard running on $pid"
	sleep 10
	kill -9 $pid
done

